COINES_INSTALL_PATH ?= ../../../..

EXAMPLE_FILE ?= fw2h.c

BHY2_INTF ?= 

COINES_BACKEND ?= COINES_BRIDGE

# Override other target definitions
TARGET = PC

include $(COINES_INSTALL_PATH)/coines.mk
