# Root of COINES installation folder
# Can be C:/COINES/v2.0 , $(HOME)/COINES/v2.0 ,etc.,
# Don't use '\' 
COINES_INSTALL_PATH ?= ../../..

EXAMPLE_FILE = fw2h.c

include $(COINES_INSTALL_PATH)/coines.mk
